language: php
dist: trusty
sudo: false

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/vcs

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

install:
  - composer install --no-interaction --no-progress --prefer-dist --ansi

script:
  - composer cs-check
  - composer test
